server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/payment_database
    username: docker
    password: SQL
  jpa:
    database-platform: postgres
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop